export function buildPatientPayload(values, { hospitalID = 0, empID = 0 } = {}) {
  const now = new Date().toISOString();
  const strOrNull = (v) => (v && String(v).trim() !== '' ? String(v).trim() : null);
  const intOrZero = (v) => (v != null && v !== '' ? Number(v) : 0);
  const dobAge = values.dobAge ?? {};

  return {
    prefix:            strOrNull(values.title),
    pfName:            values.firstName,
    pmName:            null,
    plName:            strOrNull(values.lastName),
    relation:          strOrNull(values.guardianRelation),
    rfName:            values.guardianFirstName,
    rmName:            null,
    rlName:            strOrNull(values.guardianLastName),
    sexID:             0,
    age:               0,
    ageType:           strOrNull(dobAge.unit),
    dateOfBirth:       dobAge.dob ? String(dobAge.dob) : null,
    regDateTime:       now,
    dateTime:          now,
    countryCode:       0,
    provinceID:        0,
    districtID:        0,
    tehsil:            0,
    zipcode:           0,
    house_No:          null,
    streetAddress:     strOrNull(values.presentAddress),
    city:              strOrNull(values.addressCity),
    colony:            null,
    hospitalID:        0,
    empID:             0,
    homePhone:         null,
    mobilePhone:       values.contactNo,
    nic:               strOrNull(values.cnic),
    email_address:     strOrNull(values.email ?? values.addressEmail),
    passport_No:       null,
    regNo:             null,
    barcode:           null,
    deptID:            0,
    doctorID:          0,
    diagonosis:        strOrNull([values.complaint, values.complaintOther].filter(Boolean).join(' - ')),
    patientType:       strOrNull(values.primaryCategory),
    patient_Type:      strOrNull(values.primaryCategory),
    checkupType:       strOrNull(values.checkupType),
    patient_Type_SubId: 0,
    patient_SubIdName: null,
    referenceNo:       0,
    party_ID:          0,
    party_Desg_ID:     0,
    emp_No:            null,
    empRegID:          0,
    referFrom:         null,
    to_sub_Dept:       0,
    pt_Cast:           null,
    payment_Status:    null,
    religion:          0,
    nationality:       0,
    registrationType:  null,
    room_No:           null,
    noDiary:           0,
  };
}