/** Pure data — icon values are Iconify names (e.g. mdi:home). */
export const navigation = [
  { key: 'home', label: 'Home', href: '/', icon: 'mdi:home' },
  { key: 'dashboard', label: 'Dashboard', href: '/dashboard', icon: 'mdi:view-dashboard' },
  { key: 'history', label: 'History', href: '/history', icon: 'mdi:history' },
  { key: 'cash-book', label: 'Cash Book', href: '/cash-book', icon: 'healthicons:money-bag' },
  { key: 'payment', label: 'Payment', href: '/payment', icon: 'mdi:credit-card-outline' },
  {
    key: 'opd',
    label: 'OPD',
    href: '/opd',
    icon: 'mdi:chart-bar',
    children: [
      { key: 'patient-registration', label: 'Patient Registration', href: '/opd/patient-registration' },
      { key: 'walk-in-patient', label: 'Walk-in patient', href: '/opd/walk-in-patient' },
      { key: 'advance-payment', label: 'Advance Payment', href: '/opd/advance-payment' },
      { key: 'opd-payment', label: 'Payment', href: '/opd/payment' },
      { key: 'update-dept-consultant', label: 'Update Dept & Consultant', href: '/opd/update-dept-consultant' },
      { key: 'birth-certificate', label: 'Birth Certificate form', href: '/opd/birth-certificate' },
      { key: 'duplicate-opd-slip', label: 'Duplicate OPD Slip Rep', href: '/opd/duplicate-opd-slip' },
      { key: 'emergency-registration', label: 'Emergency Registration', href: '/opd/emergency-registration' },
      { key: 'area-wise-patient-report', label: 'Area-wise Patient Report', href: '/opd/area-wise-patient-report' },
      { key: 're-visit', label: 'Re-visit', href: '/opd/re-visit' },
      { key: 'patient-search', label: 'Patient Search', href: '/opd/patient-search' },
      { key: 'employee-waive-patient', label: 'Employee for waive Patient', href: '/opd/employee-waive-patient' },
      { key: 'search-service-refund', label: 'Search Service for Refund', href: '/opd/search-service-refund' },
      { key: 'take-vital', label: 'Take Vital', href: '/opd/take-vital' },
      { key: 'rate-list', label: 'Rate List', href: '/opd/rate-list' },
      { key: 'rate-calculator', label: 'Rate Calculator', href: '/opd/rate-calculator' },
      { key: 'services-billing', label: 'Services Billing', href: '/opd/services-billing' },
    ],
  },
  { key: 'ipd', label: 'IPD', href: '/ipd', icon: 'mdi:bed' },
  {
    key: 'admin-pathology',
    label: 'Admin Pathology',
    href: '/admin-pathology',
    icon: 'mdi:microscope',
    children: [
      // {
      //   key: 'pathology-component-values',
      //   label: 'Pathology Component Values',
      //   href: '/admin-pathology/component-values',
      // },
      // {
      //   key: 'admin-services-vs-test-booking',
      //   label: 'Admin Services vs TestBooking',
      //   href: '/admin-pathology/services-vs-test-booking',
      // },
      {
        key: 'pathology-main-group',
        label: 'Pathology Main Group',
        href: '/admin-pathology/main-group',
      },
      {
        key: 'pathology-sub-group',
        label: 'Pathology Sub Group',
        href: '/admin-pathology/sub-group',
      },
      {
        key: 'pathology-test-name',
        label: 'Pathology Test Name',
        href: '/admin-pathology/test-name',
      },
      {
        key: 'pathology-component',
        label: 'Pathology Component',
        href: '/admin-pathology/pathology-component',
      },
      {
        key: 'pathology-test-range',
        label: 'Pathology Test Range',
        href: '/admin-pathology/test-range',
      },
      // {
      //   key: 'pathology-component-values-length',
      //   label: 'Pathology Component Values Length',
      //   href: '/admin-pathology/component-values-length',
      // },
      {
        key: 'pathology-test-booking',
        label: 'Pathology Test Booking',
        href: '/admin-pathology/test-booking',
      },
      {
        key: 'map-pathology-services',
        label: 'Map Pathology Services',
        href: '/admin-pathology/map-services',
      },
      // {
      //   key: 'admin-service-test-booking',
      //   label: 'Admin Service Test Booking',
      //   href: '/admin-pathology/service-test-booking',
      // },
      {
        key: 'pathology-report-consultant',
        label: 'Pathology Report Consultant',
        href: '/admin-pathology/report-consultant',
      },
      {
        key: 'add-interpretation',
        label: 'Add Interpretation',
        href: '/admin-pathology/interpretation',
      },
      // {
      //   key: 'machine-calculated-test',
      //   label: 'Machine Calculated Test',
      //   href: '/admin-pathology/machine-calculated-test',
      // },
      {
        key: 'machine-integration-compwise',
        label: 'Machine Integration Component Wise',
        href: '/admin-pathology/machine-integration-compwise',
      },
      {
        key: 'all-patient-service-report',
        label: 'All Patient Service Report',
        href: '/admin-pathology/all-patient-service-report',
      },
    ],
  },
  {
    key: 'laboratory',
    label: 'Laboratory',
    href: '/laboratory',
    icon: 'mdi:flask-outline',
    children: [
      { key: 'sample-collection', label: 'Sample Collection', href: '/laboratory/sample-collection' },
      { key: 'sample-receiving', label: 'Sample Receiving', href: '/laboratory/sample-receiving' },
      { key: 'result-entry', label: 'Result Entry', href: '/laboratory/result-entry' },
      { key: 'test-conducted', label: 'Test Conducted', href: '/laboratory/test-conducted' },
      { key: 'undelivered-reports', label: 'Undelivered Reports', href: '/laboratory/undelivered-reports' },
      { key: 'delivered-reports', label: 'Delivered Reports', href: '/laboratory/delivered-reports' },
    ],
  },
  {
    key: 'service-admin',
    label: 'Service Admin',
    href: '/service-admin',
    icon: 'mdi:account-cog-outline',
    children: [
      {
        key: 'admin-services',
        label: 'Admin Services',
        href: '/service-admin/admin-services',
      },
    ],
  },
  { key: 'diagnosis', label: 'Diagnosis', href: '/diagnosis', icon: 'mdi:file-document-outline' },
  { key: 'discount', label: 'Discount', href: '/discount', icon: 'iconamoon:discount-light' },
  {
    key: 'human-resource',
    label: 'Human Resource',
    href: '/human-resource',
    icon: 'mdi:account-group-outline',
    children: [
      {
        key: 'employee-entry',
        label: 'Add Employee',
        href: '/human-resource/employee-entry',
      },
      {
        key: 'search-all-employee',
        label: 'Search All Employee',
        href: '/human-resource/search-all-employee',
      },

      {
        key: 'add-hospital',
        label: 'Add Hospital',
        href: '/human-resource/add-hospital',
      {
        key: 'activate-employee',
        label: 'Activate Employee',
        href: '/human-resource/activate-employee',
      },
            {
        key: 'department-type',
        label: 'Add Department Type',
        href: '/human-resource/department-type',
      },
    ],
  },
  { key: 'finance-admin', label: 'Finance Admin', href: '/finance-admin', icon: 'mdi:link-variant' },
  { key: 'financial-reports', label: 'Financial Reports', href: '/financial-reports', icon: 'mdi:calculator-variant-outline' },
  { key: 'user-role', label: 'User Role & Mng.', href: '/user-role', icon: 'carbon:user' },
  { key: 'patient-discharge', label: 'Patient Discharge', href: '/patient-discharge', icon: 'mdi:bed-empty' },
  { key: 'doctor-share', label: 'Doctor Share', href: '/doctor-share', icon: 'mdi:stethoscope' },
  { key: 'examination', label: 'Examination', href: '/examination', icon: 'mdi:clipboard-text-outline' },
  { key: 'inventory', label: 'Inventory', href: '/inventory', icon: 'mdi:package-variant-closed' },
  { key: 'demand-requisition', label: 'Demand Requisition', href: '/demand-requisition', icon: 'mdi:format-list-checks' },
  { key: 'blood-bank', label: 'Blood Bank', href: '/blood-bank', icon: 'mdi:water' },
  { key: 'payroll-setup', label: 'Payroll Setup', href: '/payroll-setup', icon: 'mdi:cash-multiple' },
  { key: 'store-reports', label: 'Store Reports', href: '/store-reports', icon: 'mdi:clipboard-check-outline' },
  { key: 'pharmacy', label: 'Pharmacy', href: '/pharmacy', icon: 'mdi:pharmacy' },
  { key: 'inventory-admin', label: 'Inventory Admin', href: '/inventory-admin', icon: 'mdi:archive-outline' },
  { key: 'indent-book', label: 'Indent Book', href: '/indent-book', icon: 'mdi:book-open-outline' },
  { key: 'grn', label: 'GRN', href: '/grn', icon: 'mdi:file-document-outline' },
  { key: 'purchase-order', label: 'Purchase Order', href: '/purchase-order', icon: 'mdi:cart-outline' },
  { key: 'administration-rep', label: 'Administration Rep', href: '/administration-rep', icon: 'mdi:file-chart-outline' },
  { key: 'other-requests', label: 'Other Requests', href: '/other-requests', icon: 'mdi:file-send-outline' },
  { key: 'certificates', label: 'Certificates', href: '/certificates', icon: 'mdi:certificate-outline' },
  { key: 'radiology', label: 'Radiology', href: '/radiology', icon: 'mdi:radiology-box-outline' },
  { key: 'blood-bank-reps', label: 'Blood Bank Reps', href: '/blood-bank-reps', icon: 'mdi:calendar-month-outline' },
  { key: 'refund', label: 'Refund', href: '/refund', icon: 'mdi:cash-refund' },
  { key: 'quotation', label: 'Quotation', href: '/quotation', icon: 'mdi:file-document-edit-outline' },
];

export const footerLinks = [
  { key: 'help', label: 'Help', href: '/help', icon: 'mdi:help-circle-outline' },
  { key: 'logout', label: 'Logout', href: '/logout', icon: 'mdi:logout' },
];
